#pragma once
#include <stdio.h>
#include <string>
#include "srpc/rpc_define.h"
#include "cloud_disk.pb.h"

namespace cloud
{

namespace disk
{

namespace AuthService
{

/*
 * Server codes
 * Generated by SRPC
 */

class Service : public srpc::RPCService
{
public:
	// please implement these methods in server.cc

	virtual void Register(RegisterRequest *request, RegisterResponse *response,
					srpc::RPCContext *ctx) = 0;

	virtual void Login(LoginRequest *request, LoginResponse *response,
					srpc::RPCContext *ctx) = 0;

	virtual void VerifyToken(VerifyTokenRequest *request, VerifyTokenResponse *response,
					srpc::RPCContext *ctx) = 0;

public:
	Service();
};

/*
 * Client codes
 * Generated by SRPC
 */

using RegisterDone = std::function<void (RegisterResponse *, srpc::RPCContext *)>;
using LoginDone = std::function<void (LoginResponse *, srpc::RPCContext *)>;
using VerifyTokenDone = std::function<void (VerifyTokenResponse *, srpc::RPCContext *)>;

class SRPCClient : public srpc::SRPCClient
{
public:
	void Register(const RegisterRequest *req, RegisterDone done);
	void Register(const RegisterRequest *req, RegisterResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<RegisterResponse, srpc::RPCSyncContext>> async_Register(const RegisterRequest *req);

	void Login(const LoginRequest *req, LoginDone done);
	void Login(const LoginRequest *req, LoginResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<LoginResponse, srpc::RPCSyncContext>> async_Login(const LoginRequest *req);

	void VerifyToken(const VerifyTokenRequest *req, VerifyTokenDone done);
	void VerifyToken(const VerifyTokenRequest *req, VerifyTokenResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<VerifyTokenResponse, srpc::RPCSyncContext>> async_VerifyToken(const VerifyTokenRequest *req);

public:
	SRPCClient(const char *host, unsigned short port);
	SRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::SRPCClientTask *create_Register_task(RegisterDone done);
	srpc::SRPCClientTask *create_Login_task(LoginDone done);
	srpc::SRPCClientTask *create_VerifyToken_task(VerifyTokenDone done);
};

class SRPCHttpClient : public srpc::SRPCHttpClient
{
public:
	void Register(const RegisterRequest *req, RegisterDone done);
	void Register(const RegisterRequest *req, RegisterResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<RegisterResponse, srpc::RPCSyncContext>> async_Register(const RegisterRequest *req);

	void Login(const LoginRequest *req, LoginDone done);
	void Login(const LoginRequest *req, LoginResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<LoginResponse, srpc::RPCSyncContext>> async_Login(const LoginRequest *req);

	void VerifyToken(const VerifyTokenRequest *req, VerifyTokenDone done);
	void VerifyToken(const VerifyTokenRequest *req, VerifyTokenResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<VerifyTokenResponse, srpc::RPCSyncContext>> async_VerifyToken(const VerifyTokenRequest *req);

public:
	SRPCHttpClient(const char *host, unsigned short port);
	SRPCHttpClient(const struct srpc::RPCClientParams *params);

public:
	srpc::SRPCHttpClientTask *create_Register_task(RegisterDone done);
	srpc::SRPCHttpClientTask *create_Login_task(LoginDone done);
	srpc::SRPCHttpClientTask *create_VerifyToken_task(VerifyTokenDone done);
};

class BRPCClient : public srpc::BRPCClient
{
public:
	void Register(const RegisterRequest *req, RegisterDone done);
	void Register(const RegisterRequest *req, RegisterResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<RegisterResponse, srpc::RPCSyncContext>> async_Register(const RegisterRequest *req);

	void Login(const LoginRequest *req, LoginDone done);
	void Login(const LoginRequest *req, LoginResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<LoginResponse, srpc::RPCSyncContext>> async_Login(const LoginRequest *req);

	void VerifyToken(const VerifyTokenRequest *req, VerifyTokenDone done);
	void VerifyToken(const VerifyTokenRequest *req, VerifyTokenResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<VerifyTokenResponse, srpc::RPCSyncContext>> async_VerifyToken(const VerifyTokenRequest *req);

public:
	BRPCClient(const char *host, unsigned short port);
	BRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::BRPCClientTask *create_Register_task(RegisterDone done);
	srpc::BRPCClientTask *create_Login_task(LoginDone done);
	srpc::BRPCClientTask *create_VerifyToken_task(VerifyTokenDone done);
};

class TRPCClient : public srpc::TRPCClient
{
public:
	void Register(const RegisterRequest *req, RegisterDone done);
	void Register(const RegisterRequest *req, RegisterResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<RegisterResponse, srpc::RPCSyncContext>> async_Register(const RegisterRequest *req);

	void Login(const LoginRequest *req, LoginDone done);
	void Login(const LoginRequest *req, LoginResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<LoginResponse, srpc::RPCSyncContext>> async_Login(const LoginRequest *req);

	void VerifyToken(const VerifyTokenRequest *req, VerifyTokenDone done);
	void VerifyToken(const VerifyTokenRequest *req, VerifyTokenResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<VerifyTokenResponse, srpc::RPCSyncContext>> async_VerifyToken(const VerifyTokenRequest *req);

public:
	TRPCClient(const char *host, unsigned short port);
	TRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::TRPCClientTask *create_Register_task(RegisterDone done);
	srpc::TRPCClientTask *create_Login_task(LoginDone done);
	srpc::TRPCClientTask *create_VerifyToken_task(VerifyTokenDone done);
};

class TRPCHttpClient : public srpc::TRPCHttpClient
{
public:
	void Register(const RegisterRequest *req, RegisterDone done);
	void Register(const RegisterRequest *req, RegisterResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<RegisterResponse, srpc::RPCSyncContext>> async_Register(const RegisterRequest *req);

	void Login(const LoginRequest *req, LoginDone done);
	void Login(const LoginRequest *req, LoginResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<LoginResponse, srpc::RPCSyncContext>> async_Login(const LoginRequest *req);

	void VerifyToken(const VerifyTokenRequest *req, VerifyTokenDone done);
	void VerifyToken(const VerifyTokenRequest *req, VerifyTokenResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<VerifyTokenResponse, srpc::RPCSyncContext>> async_VerifyToken(const VerifyTokenRequest *req);

public:
	TRPCHttpClient(const char *host, unsigned short port);
	TRPCHttpClient(const struct srpc::RPCClientParams *params);

public:
	srpc::TRPCHttpClientTask *create_Register_task(RegisterDone done);
	srpc::TRPCHttpClientTask *create_Login_task(LoginDone done);
	srpc::TRPCHttpClientTask *create_VerifyToken_task(VerifyTokenDone done);
};

///// implements detials /////

inline Service::Service(): srpc::RPCService("cloud.disk.AuthService")
{
	this->srpc::RPCService::add_method("Register",
		[this](srpc::RPCWorker& worker) ->int {
			return ServiceRPCCallImpl(this, worker, &Service::Register);
		});

	this->srpc::RPCService::add_method("Login",
		[this](srpc::RPCWorker& worker) ->int {
			return ServiceRPCCallImpl(this, worker, &Service::Login);
		});

	this->srpc::RPCService::add_method("VerifyToken",
		[this](srpc::RPCWorker& worker) ->int {
			return ServiceRPCCallImpl(this, worker, &Service::VerifyToken);
		});
}

inline SRPCClient::SRPCClient(const char *host, unsigned short port):
	srpc::SRPCClient("cloud.disk.AuthService")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::SRPCClient::init(&params);
}

inline SRPCClient::SRPCClient(const struct srpc::RPCClientParams *params):
	srpc::SRPCClient("cloud.disk.AuthService")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::SRPCClient::init(temp);
}

inline void SRPCClient::Register(const RegisterRequest *req, RegisterDone done)
{
	auto *task = this->create_rpc_client_task("Register", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCClient::Register(const RegisterRequest *req, RegisterResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_Register(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<RegisterResponse, srpc::RPCSyncContext>> SRPCClient::async_Register(const RegisterRequest *req)
{
	using RESULT = std::pair<RegisterResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<RegisterResponse>("Register", srpc::RPCAsyncFutureCallback<RegisterResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void SRPCClient::Login(const LoginRequest *req, LoginDone done)
{
	auto *task = this->create_rpc_client_task("Login", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCClient::Login(const LoginRequest *req, LoginResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_Login(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<LoginResponse, srpc::RPCSyncContext>> SRPCClient::async_Login(const LoginRequest *req)
{
	using RESULT = std::pair<LoginResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<LoginResponse>("Login", srpc::RPCAsyncFutureCallback<LoginResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void SRPCClient::VerifyToken(const VerifyTokenRequest *req, VerifyTokenDone done)
{
	auto *task = this->create_rpc_client_task("VerifyToken", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCClient::VerifyToken(const VerifyTokenRequest *req, VerifyTokenResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_VerifyToken(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<VerifyTokenResponse, srpc::RPCSyncContext>> SRPCClient::async_VerifyToken(const VerifyTokenRequest *req)
{
	using RESULT = std::pair<VerifyTokenResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<VerifyTokenResponse>("VerifyToken", srpc::RPCAsyncFutureCallback<VerifyTokenResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::SRPCClientTask *SRPCClient::create_Register_task(RegisterDone done)
{
	return this->create_rpc_client_task("Register", std::move(done));
}

inline srpc::SRPCClientTask *SRPCClient::create_Login_task(LoginDone done)
{
	return this->create_rpc_client_task("Login", std::move(done));
}

inline srpc::SRPCClientTask *SRPCClient::create_VerifyToken_task(VerifyTokenDone done)
{
	return this->create_rpc_client_task("VerifyToken", std::move(done));
}

inline SRPCHttpClient::SRPCHttpClient(const char *host, unsigned short port):
	srpc::SRPCHttpClient("cloud/disk/AuthService")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::SRPCHttpClient::init(&params);
}

inline SRPCHttpClient::SRPCHttpClient(const struct srpc::RPCClientParams *params):
	srpc::SRPCHttpClient("cloud/disk/AuthService")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::SRPCHttpClient::init(temp);
}

inline void SRPCHttpClient::Register(const RegisterRequest *req, RegisterDone done)
{
	auto *task = this->create_rpc_client_task("Register", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCHttpClient::Register(const RegisterRequest *req, RegisterResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_Register(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<RegisterResponse, srpc::RPCSyncContext>> SRPCHttpClient::async_Register(const RegisterRequest *req)
{
	using RESULT = std::pair<RegisterResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<RegisterResponse>("Register", srpc::RPCAsyncFutureCallback<RegisterResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void SRPCHttpClient::Login(const LoginRequest *req, LoginDone done)
{
	auto *task = this->create_rpc_client_task("Login", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCHttpClient::Login(const LoginRequest *req, LoginResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_Login(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<LoginResponse, srpc::RPCSyncContext>> SRPCHttpClient::async_Login(const LoginRequest *req)
{
	using RESULT = std::pair<LoginResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<LoginResponse>("Login", srpc::RPCAsyncFutureCallback<LoginResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void SRPCHttpClient::VerifyToken(const VerifyTokenRequest *req, VerifyTokenDone done)
{
	auto *task = this->create_rpc_client_task("VerifyToken", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCHttpClient::VerifyToken(const VerifyTokenRequest *req, VerifyTokenResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_VerifyToken(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<VerifyTokenResponse, srpc::RPCSyncContext>> SRPCHttpClient::async_VerifyToken(const VerifyTokenRequest *req)
{
	using RESULT = std::pair<VerifyTokenResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<VerifyTokenResponse>("VerifyToken", srpc::RPCAsyncFutureCallback<VerifyTokenResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::SRPCHttpClientTask *SRPCHttpClient::create_Register_task(RegisterDone done)
{
	return this->create_rpc_client_task("Register", std::move(done));
}

inline srpc::SRPCHttpClientTask *SRPCHttpClient::create_Login_task(LoginDone done)
{
	return this->create_rpc_client_task("Login", std::move(done));
}

inline srpc::SRPCHttpClientTask *SRPCHttpClient::create_VerifyToken_task(VerifyTokenDone done)
{
	return this->create_rpc_client_task("VerifyToken", std::move(done));
}

inline BRPCClient::BRPCClient(const char *host, unsigned short port):
	srpc::BRPCClient("cloud.disk.AuthService")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::BRPCClient::init(&params);
}

inline BRPCClient::BRPCClient(const struct srpc::RPCClientParams *params):
	srpc::BRPCClient("cloud.disk.AuthService")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::BRPCClient::init(temp);
}

inline void BRPCClient::Register(const RegisterRequest *req, RegisterDone done)
{
	auto *task = this->create_rpc_client_task("Register", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void BRPCClient::Register(const RegisterRequest *req, RegisterResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_Register(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<RegisterResponse, srpc::RPCSyncContext>> BRPCClient::async_Register(const RegisterRequest *req)
{
	using RESULT = std::pair<RegisterResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<RegisterResponse>("Register", srpc::RPCAsyncFutureCallback<RegisterResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void BRPCClient::Login(const LoginRequest *req, LoginDone done)
{
	auto *task = this->create_rpc_client_task("Login", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void BRPCClient::Login(const LoginRequest *req, LoginResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_Login(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<LoginResponse, srpc::RPCSyncContext>> BRPCClient::async_Login(const LoginRequest *req)
{
	using RESULT = std::pair<LoginResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<LoginResponse>("Login", srpc::RPCAsyncFutureCallback<LoginResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void BRPCClient::VerifyToken(const VerifyTokenRequest *req, VerifyTokenDone done)
{
	auto *task = this->create_rpc_client_task("VerifyToken", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void BRPCClient::VerifyToken(const VerifyTokenRequest *req, VerifyTokenResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_VerifyToken(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<VerifyTokenResponse, srpc::RPCSyncContext>> BRPCClient::async_VerifyToken(const VerifyTokenRequest *req)
{
	using RESULT = std::pair<VerifyTokenResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<VerifyTokenResponse>("VerifyToken", srpc::RPCAsyncFutureCallback<VerifyTokenResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::BRPCClientTask *BRPCClient::create_Register_task(RegisterDone done)
{
	return this->create_rpc_client_task("Register", std::move(done));
}

inline srpc::BRPCClientTask *BRPCClient::create_Login_task(LoginDone done)
{
	return this->create_rpc_client_task("Login", std::move(done));
}

inline srpc::BRPCClientTask *BRPCClient::create_VerifyToken_task(VerifyTokenDone done)
{
	return this->create_rpc_client_task("VerifyToken", std::move(done));
}

inline TRPCClient::TRPCClient(const char *host, unsigned short port):
	srpc::TRPCClient("cloud.disk.AuthService")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::TRPCClient::init(&params);
}

inline TRPCClient::TRPCClient(const struct srpc::RPCClientParams *params):
	srpc::TRPCClient("cloud.disk.AuthService")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::TRPCClient::init(temp);
}

inline void TRPCClient::Register(const RegisterRequest *req, RegisterDone done)
{
	auto *task = this->create_rpc_client_task("/cloud.disk.AuthService/Register", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCClient::Register(const RegisterRequest *req, RegisterResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_Register(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<RegisterResponse, srpc::RPCSyncContext>> TRPCClient::async_Register(const RegisterRequest *req)
{
	using RESULT = std::pair<RegisterResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<RegisterResponse>("/cloud.disk.AuthService/Register", srpc::RPCAsyncFutureCallback<RegisterResponse>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void TRPCClient::Login(const LoginRequest *req, LoginDone done)
{
	auto *task = this->create_rpc_client_task("/cloud.disk.AuthService/Login", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCClient::Login(const LoginRequest *req, LoginResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_Login(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<LoginResponse, srpc::RPCSyncContext>> TRPCClient::async_Login(const LoginRequest *req)
{
	using RESULT = std::pair<LoginResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<LoginResponse>("/cloud.disk.AuthService/Login", srpc::RPCAsyncFutureCallback<LoginResponse>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void TRPCClient::VerifyToken(const VerifyTokenRequest *req, VerifyTokenDone done)
{
	auto *task = this->create_rpc_client_task("/cloud.disk.AuthService/VerifyToken", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCClient::VerifyToken(const VerifyTokenRequest *req, VerifyTokenResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_VerifyToken(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<VerifyTokenResponse, srpc::RPCSyncContext>> TRPCClient::async_VerifyToken(const VerifyTokenRequest *req)
{
	using RESULT = std::pair<VerifyTokenResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<VerifyTokenResponse>("/cloud.disk.AuthService/VerifyToken", srpc::RPCAsyncFutureCallback<VerifyTokenResponse>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::TRPCClientTask *TRPCClient::create_Register_task(RegisterDone done)
{
	auto *task = this->create_rpc_client_task("/cloud.disk.AuthService/Register", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline srpc::TRPCClientTask *TRPCClient::create_Login_task(LoginDone done)
{
	auto *task = this->create_rpc_client_task("/cloud.disk.AuthService/Login", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline srpc::TRPCClientTask *TRPCClient::create_VerifyToken_task(VerifyTokenDone done)
{
	auto *task = this->create_rpc_client_task("/cloud.disk.AuthService/VerifyToken", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline TRPCHttpClient::TRPCHttpClient(const char *host, unsigned short port):
	srpc::TRPCHttpClient("cloud.disk.AuthService")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::TRPCHttpClient::init(&params);
}

inline TRPCHttpClient::TRPCHttpClient(const struct srpc::RPCClientParams *params):
	srpc::TRPCHttpClient("cloud.disk.AuthService")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::TRPCHttpClient::init(temp);
}

inline void TRPCHttpClient::Register(const RegisterRequest *req, RegisterDone done)
{
	auto *task = this->create_rpc_client_task("Register", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCHttpClient::Register(const RegisterRequest *req, RegisterResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_Register(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<RegisterResponse, srpc::RPCSyncContext>> TRPCHttpClient::async_Register(const RegisterRequest *req)
{
	using RESULT = std::pair<RegisterResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<RegisterResponse>("Register", srpc::RPCAsyncFutureCallback<RegisterResponse>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void TRPCHttpClient::Login(const LoginRequest *req, LoginDone done)
{
	auto *task = this->create_rpc_client_task("Login", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCHttpClient::Login(const LoginRequest *req, LoginResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_Login(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<LoginResponse, srpc::RPCSyncContext>> TRPCHttpClient::async_Login(const LoginRequest *req)
{
	using RESULT = std::pair<LoginResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<LoginResponse>("Login", srpc::RPCAsyncFutureCallback<LoginResponse>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void TRPCHttpClient::VerifyToken(const VerifyTokenRequest *req, VerifyTokenDone done)
{
	auto *task = this->create_rpc_client_task("VerifyToken", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCHttpClient::VerifyToken(const VerifyTokenRequest *req, VerifyTokenResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_VerifyToken(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<VerifyTokenResponse, srpc::RPCSyncContext>> TRPCHttpClient::async_VerifyToken(const VerifyTokenRequest *req)
{
	using RESULT = std::pair<VerifyTokenResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<VerifyTokenResponse>("VerifyToken", srpc::RPCAsyncFutureCallback<VerifyTokenResponse>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::TRPCHttpClientTask *TRPCHttpClient::create_Register_task(RegisterDone done)
{
	auto *task = this->create_rpc_client_task("Register", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline srpc::TRPCHttpClientTask *TRPCHttpClient::create_Login_task(LoginDone done)
{
	auto *task = this->create_rpc_client_task("Login", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline srpc::TRPCHttpClientTask *TRPCHttpClient::create_VerifyToken_task(VerifyTokenDone done)
{
	auto *task = this->create_rpc_client_task("VerifyToken", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

} // end namespace AuthService


namespace UserService
{

/*
 * Server codes
 * Generated by SRPC
 */

class Service : public srpc::RPCService
{
public:
	// please implement these methods in server.cc

	virtual void GetUserProfile(GetUserProfileRequest *request, GetUserProfileResponse *response,
					srpc::RPCContext *ctx) = 0;

public:
	Service();
};

/*
 * Client codes
 * Generated by SRPC
 */

using GetUserProfileDone = std::function<void (GetUserProfileResponse *, srpc::RPCContext *)>;

class SRPCClient : public srpc::SRPCClient
{
public:
	void GetUserProfile(const GetUserProfileRequest *req, GetUserProfileDone done);
	void GetUserProfile(const GetUserProfileRequest *req, GetUserProfileResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<GetUserProfileResponse, srpc::RPCSyncContext>> async_GetUserProfile(const GetUserProfileRequest *req);

public:
	SRPCClient(const char *host, unsigned short port);
	SRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::SRPCClientTask *create_GetUserProfile_task(GetUserProfileDone done);
};

class SRPCHttpClient : public srpc::SRPCHttpClient
{
public:
	void GetUserProfile(const GetUserProfileRequest *req, GetUserProfileDone done);
	void GetUserProfile(const GetUserProfileRequest *req, GetUserProfileResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<GetUserProfileResponse, srpc::RPCSyncContext>> async_GetUserProfile(const GetUserProfileRequest *req);

public:
	SRPCHttpClient(const char *host, unsigned short port);
	SRPCHttpClient(const struct srpc::RPCClientParams *params);

public:
	srpc::SRPCHttpClientTask *create_GetUserProfile_task(GetUserProfileDone done);
};

class BRPCClient : public srpc::BRPCClient
{
public:
	void GetUserProfile(const GetUserProfileRequest *req, GetUserProfileDone done);
	void GetUserProfile(const GetUserProfileRequest *req, GetUserProfileResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<GetUserProfileResponse, srpc::RPCSyncContext>> async_GetUserProfile(const GetUserProfileRequest *req);

public:
	BRPCClient(const char *host, unsigned short port);
	BRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::BRPCClientTask *create_GetUserProfile_task(GetUserProfileDone done);
};

class TRPCClient : public srpc::TRPCClient
{
public:
	void GetUserProfile(const GetUserProfileRequest *req, GetUserProfileDone done);
	void GetUserProfile(const GetUserProfileRequest *req, GetUserProfileResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<GetUserProfileResponse, srpc::RPCSyncContext>> async_GetUserProfile(const GetUserProfileRequest *req);

public:
	TRPCClient(const char *host, unsigned short port);
	TRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::TRPCClientTask *create_GetUserProfile_task(GetUserProfileDone done);
};

class TRPCHttpClient : public srpc::TRPCHttpClient
{
public:
	void GetUserProfile(const GetUserProfileRequest *req, GetUserProfileDone done);
	void GetUserProfile(const GetUserProfileRequest *req, GetUserProfileResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<GetUserProfileResponse, srpc::RPCSyncContext>> async_GetUserProfile(const GetUserProfileRequest *req);

public:
	TRPCHttpClient(const char *host, unsigned short port);
	TRPCHttpClient(const struct srpc::RPCClientParams *params);

public:
	srpc::TRPCHttpClientTask *create_GetUserProfile_task(GetUserProfileDone done);
};

///// implements detials /////

inline Service::Service(): srpc::RPCService("cloud.disk.UserService")
{
	this->srpc::RPCService::add_method("GetUserProfile",
		[this](srpc::RPCWorker& worker) ->int {
			return ServiceRPCCallImpl(this, worker, &Service::GetUserProfile);
		});
}

inline SRPCClient::SRPCClient(const char *host, unsigned short port):
	srpc::SRPCClient("cloud.disk.UserService")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::SRPCClient::init(&params);
}

inline SRPCClient::SRPCClient(const struct srpc::RPCClientParams *params):
	srpc::SRPCClient("cloud.disk.UserService")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::SRPCClient::init(temp);
}

inline void SRPCClient::GetUserProfile(const GetUserProfileRequest *req, GetUserProfileDone done)
{
	auto *task = this->create_rpc_client_task("GetUserProfile", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCClient::GetUserProfile(const GetUserProfileRequest *req, GetUserProfileResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_GetUserProfile(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<GetUserProfileResponse, srpc::RPCSyncContext>> SRPCClient::async_GetUserProfile(const GetUserProfileRequest *req)
{
	using RESULT = std::pair<GetUserProfileResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<GetUserProfileResponse>("GetUserProfile", srpc::RPCAsyncFutureCallback<GetUserProfileResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::SRPCClientTask *SRPCClient::create_GetUserProfile_task(GetUserProfileDone done)
{
	return this->create_rpc_client_task("GetUserProfile", std::move(done));
}

inline SRPCHttpClient::SRPCHttpClient(const char *host, unsigned short port):
	srpc::SRPCHttpClient("cloud/disk/UserService")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::SRPCHttpClient::init(&params);
}

inline SRPCHttpClient::SRPCHttpClient(const struct srpc::RPCClientParams *params):
	srpc::SRPCHttpClient("cloud/disk/UserService")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::SRPCHttpClient::init(temp);
}

inline void SRPCHttpClient::GetUserProfile(const GetUserProfileRequest *req, GetUserProfileDone done)
{
	auto *task = this->create_rpc_client_task("GetUserProfile", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCHttpClient::GetUserProfile(const GetUserProfileRequest *req, GetUserProfileResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_GetUserProfile(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<GetUserProfileResponse, srpc::RPCSyncContext>> SRPCHttpClient::async_GetUserProfile(const GetUserProfileRequest *req)
{
	using RESULT = std::pair<GetUserProfileResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<GetUserProfileResponse>("GetUserProfile", srpc::RPCAsyncFutureCallback<GetUserProfileResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::SRPCHttpClientTask *SRPCHttpClient::create_GetUserProfile_task(GetUserProfileDone done)
{
	return this->create_rpc_client_task("GetUserProfile", std::move(done));
}

inline BRPCClient::BRPCClient(const char *host, unsigned short port):
	srpc::BRPCClient("cloud.disk.UserService")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::BRPCClient::init(&params);
}

inline BRPCClient::BRPCClient(const struct srpc::RPCClientParams *params):
	srpc::BRPCClient("cloud.disk.UserService")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::BRPCClient::init(temp);
}

inline void BRPCClient::GetUserProfile(const GetUserProfileRequest *req, GetUserProfileDone done)
{
	auto *task = this->create_rpc_client_task("GetUserProfile", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void BRPCClient::GetUserProfile(const GetUserProfileRequest *req, GetUserProfileResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_GetUserProfile(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<GetUserProfileResponse, srpc::RPCSyncContext>> BRPCClient::async_GetUserProfile(const GetUserProfileRequest *req)
{
	using RESULT = std::pair<GetUserProfileResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<GetUserProfileResponse>("GetUserProfile", srpc::RPCAsyncFutureCallback<GetUserProfileResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::BRPCClientTask *BRPCClient::create_GetUserProfile_task(GetUserProfileDone done)
{
	return this->create_rpc_client_task("GetUserProfile", std::move(done));
}

inline TRPCClient::TRPCClient(const char *host, unsigned short port):
	srpc::TRPCClient("cloud.disk.UserService")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::TRPCClient::init(&params);
}

inline TRPCClient::TRPCClient(const struct srpc::RPCClientParams *params):
	srpc::TRPCClient("cloud.disk.UserService")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::TRPCClient::init(temp);
}

inline void TRPCClient::GetUserProfile(const GetUserProfileRequest *req, GetUserProfileDone done)
{
	auto *task = this->create_rpc_client_task("/cloud.disk.UserService/GetUserProfile", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCClient::GetUserProfile(const GetUserProfileRequest *req, GetUserProfileResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_GetUserProfile(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<GetUserProfileResponse, srpc::RPCSyncContext>> TRPCClient::async_GetUserProfile(const GetUserProfileRequest *req)
{
	using RESULT = std::pair<GetUserProfileResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<GetUserProfileResponse>("/cloud.disk.UserService/GetUserProfile", srpc::RPCAsyncFutureCallback<GetUserProfileResponse>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::TRPCClientTask *TRPCClient::create_GetUserProfile_task(GetUserProfileDone done)
{
	auto *task = this->create_rpc_client_task("/cloud.disk.UserService/GetUserProfile", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline TRPCHttpClient::TRPCHttpClient(const char *host, unsigned short port):
	srpc::TRPCHttpClient("cloud.disk.UserService")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::TRPCHttpClient::init(&params);
}

inline TRPCHttpClient::TRPCHttpClient(const struct srpc::RPCClientParams *params):
	srpc::TRPCHttpClient("cloud.disk.UserService")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::TRPCHttpClient::init(temp);
}

inline void TRPCHttpClient::GetUserProfile(const GetUserProfileRequest *req, GetUserProfileDone done)
{
	auto *task = this->create_rpc_client_task("GetUserProfile", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCHttpClient::GetUserProfile(const GetUserProfileRequest *req, GetUserProfileResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_GetUserProfile(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<GetUserProfileResponse, srpc::RPCSyncContext>> TRPCHttpClient::async_GetUserProfile(const GetUserProfileRequest *req)
{
	using RESULT = std::pair<GetUserProfileResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<GetUserProfileResponse>("GetUserProfile", srpc::RPCAsyncFutureCallback<GetUserProfileResponse>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::TRPCHttpClientTask *TRPCHttpClient::create_GetUserProfile_task(GetUserProfileDone done)
{
	auto *task = this->create_rpc_client_task("GetUserProfile", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

} // end namespace UserService


namespace FileMetaService
{

/*
 * Server codes
 * Generated by SRPC
 */

class Service : public srpc::RPCService
{
public:
	// please implement these methods in server.cc

	virtual void ListFiles(ListFilesRequest *request, ListFilesResponse *response,
					srpc::RPCContext *ctx) = 0;

	virtual void CreateFile(CreateFileRequest *request, CreateFileResponse *response,
					srpc::RPCContext *ctx) = 0;

	virtual void GetFileForDownload(GetFileForDownloadRequest *request, GetFileForDownloadResponse *response,
					srpc::RPCContext *ctx) = 0;

public:
	Service();
};

/*
 * Client codes
 * Generated by SRPC
 */

using ListFilesDone = std::function<void (ListFilesResponse *, srpc::RPCContext *)>;
using CreateFileDone = std::function<void (CreateFileResponse *, srpc::RPCContext *)>;
using GetFileForDownloadDone = std::function<void (GetFileForDownloadResponse *, srpc::RPCContext *)>;

class SRPCClient : public srpc::SRPCClient
{
public:
	void ListFiles(const ListFilesRequest *req, ListFilesDone done);
	void ListFiles(const ListFilesRequest *req, ListFilesResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<ListFilesResponse, srpc::RPCSyncContext>> async_ListFiles(const ListFilesRequest *req);

	void CreateFile(const CreateFileRequest *req, CreateFileDone done);
	void CreateFile(const CreateFileRequest *req, CreateFileResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<CreateFileResponse, srpc::RPCSyncContext>> async_CreateFile(const CreateFileRequest *req);

	void GetFileForDownload(const GetFileForDownloadRequest *req, GetFileForDownloadDone done);
	void GetFileForDownload(const GetFileForDownloadRequest *req, GetFileForDownloadResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<GetFileForDownloadResponse, srpc::RPCSyncContext>> async_GetFileForDownload(const GetFileForDownloadRequest *req);

public:
	SRPCClient(const char *host, unsigned short port);
	SRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::SRPCClientTask *create_ListFiles_task(ListFilesDone done);
	srpc::SRPCClientTask *create_CreateFile_task(CreateFileDone done);
	srpc::SRPCClientTask *create_GetFileForDownload_task(GetFileForDownloadDone done);
};

class SRPCHttpClient : public srpc::SRPCHttpClient
{
public:
	void ListFiles(const ListFilesRequest *req, ListFilesDone done);
	void ListFiles(const ListFilesRequest *req, ListFilesResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<ListFilesResponse, srpc::RPCSyncContext>> async_ListFiles(const ListFilesRequest *req);

	void CreateFile(const CreateFileRequest *req, CreateFileDone done);
	void CreateFile(const CreateFileRequest *req, CreateFileResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<CreateFileResponse, srpc::RPCSyncContext>> async_CreateFile(const CreateFileRequest *req);

	void GetFileForDownload(const GetFileForDownloadRequest *req, GetFileForDownloadDone done);
	void GetFileForDownload(const GetFileForDownloadRequest *req, GetFileForDownloadResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<GetFileForDownloadResponse, srpc::RPCSyncContext>> async_GetFileForDownload(const GetFileForDownloadRequest *req);

public:
	SRPCHttpClient(const char *host, unsigned short port);
	SRPCHttpClient(const struct srpc::RPCClientParams *params);

public:
	srpc::SRPCHttpClientTask *create_ListFiles_task(ListFilesDone done);
	srpc::SRPCHttpClientTask *create_CreateFile_task(CreateFileDone done);
	srpc::SRPCHttpClientTask *create_GetFileForDownload_task(GetFileForDownloadDone done);
};

class BRPCClient : public srpc::BRPCClient
{
public:
	void ListFiles(const ListFilesRequest *req, ListFilesDone done);
	void ListFiles(const ListFilesRequest *req, ListFilesResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<ListFilesResponse, srpc::RPCSyncContext>> async_ListFiles(const ListFilesRequest *req);

	void CreateFile(const CreateFileRequest *req, CreateFileDone done);
	void CreateFile(const CreateFileRequest *req, CreateFileResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<CreateFileResponse, srpc::RPCSyncContext>> async_CreateFile(const CreateFileRequest *req);

	void GetFileForDownload(const GetFileForDownloadRequest *req, GetFileForDownloadDone done);
	void GetFileForDownload(const GetFileForDownloadRequest *req, GetFileForDownloadResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<GetFileForDownloadResponse, srpc::RPCSyncContext>> async_GetFileForDownload(const GetFileForDownloadRequest *req);

public:
	BRPCClient(const char *host, unsigned short port);
	BRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::BRPCClientTask *create_ListFiles_task(ListFilesDone done);
	srpc::BRPCClientTask *create_CreateFile_task(CreateFileDone done);
	srpc::BRPCClientTask *create_GetFileForDownload_task(GetFileForDownloadDone done);
};

class TRPCClient : public srpc::TRPCClient
{
public:
	void ListFiles(const ListFilesRequest *req, ListFilesDone done);
	void ListFiles(const ListFilesRequest *req, ListFilesResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<ListFilesResponse, srpc::RPCSyncContext>> async_ListFiles(const ListFilesRequest *req);

	void CreateFile(const CreateFileRequest *req, CreateFileDone done);
	void CreateFile(const CreateFileRequest *req, CreateFileResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<CreateFileResponse, srpc::RPCSyncContext>> async_CreateFile(const CreateFileRequest *req);

	void GetFileForDownload(const GetFileForDownloadRequest *req, GetFileForDownloadDone done);
	void GetFileForDownload(const GetFileForDownloadRequest *req, GetFileForDownloadResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<GetFileForDownloadResponse, srpc::RPCSyncContext>> async_GetFileForDownload(const GetFileForDownloadRequest *req);

public:
	TRPCClient(const char *host, unsigned short port);
	TRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::TRPCClientTask *create_ListFiles_task(ListFilesDone done);
	srpc::TRPCClientTask *create_CreateFile_task(CreateFileDone done);
	srpc::TRPCClientTask *create_GetFileForDownload_task(GetFileForDownloadDone done);
};

class TRPCHttpClient : public srpc::TRPCHttpClient
{
public:
	void ListFiles(const ListFilesRequest *req, ListFilesDone done);
	void ListFiles(const ListFilesRequest *req, ListFilesResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<ListFilesResponse, srpc::RPCSyncContext>> async_ListFiles(const ListFilesRequest *req);

	void CreateFile(const CreateFileRequest *req, CreateFileDone done);
	void CreateFile(const CreateFileRequest *req, CreateFileResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<CreateFileResponse, srpc::RPCSyncContext>> async_CreateFile(const CreateFileRequest *req);

	void GetFileForDownload(const GetFileForDownloadRequest *req, GetFileForDownloadDone done);
	void GetFileForDownload(const GetFileForDownloadRequest *req, GetFileForDownloadResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<GetFileForDownloadResponse, srpc::RPCSyncContext>> async_GetFileForDownload(const GetFileForDownloadRequest *req);

public:
	TRPCHttpClient(const char *host, unsigned short port);
	TRPCHttpClient(const struct srpc::RPCClientParams *params);

public:
	srpc::TRPCHttpClientTask *create_ListFiles_task(ListFilesDone done);
	srpc::TRPCHttpClientTask *create_CreateFile_task(CreateFileDone done);
	srpc::TRPCHttpClientTask *create_GetFileForDownload_task(GetFileForDownloadDone done);
};

///// implements detials /////

inline Service::Service(): srpc::RPCService("cloud.disk.FileMetaService")
{
	this->srpc::RPCService::add_method("ListFiles",
		[this](srpc::RPCWorker& worker) ->int {
			return ServiceRPCCallImpl(this, worker, &Service::ListFiles);
		});

	this->srpc::RPCService::add_method("CreateFile",
		[this](srpc::RPCWorker& worker) ->int {
			return ServiceRPCCallImpl(this, worker, &Service::CreateFile);
		});

	this->srpc::RPCService::add_method("GetFileForDownload",
		[this](srpc::RPCWorker& worker) ->int {
			return ServiceRPCCallImpl(this, worker, &Service::GetFileForDownload);
		});
}

inline SRPCClient::SRPCClient(const char *host, unsigned short port):
	srpc::SRPCClient("cloud.disk.FileMetaService")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::SRPCClient::init(&params);
}

inline SRPCClient::SRPCClient(const struct srpc::RPCClientParams *params):
	srpc::SRPCClient("cloud.disk.FileMetaService")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::SRPCClient::init(temp);
}

inline void SRPCClient::ListFiles(const ListFilesRequest *req, ListFilesDone done)
{
	auto *task = this->create_rpc_client_task("ListFiles", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCClient::ListFiles(const ListFilesRequest *req, ListFilesResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_ListFiles(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<ListFilesResponse, srpc::RPCSyncContext>> SRPCClient::async_ListFiles(const ListFilesRequest *req)
{
	using RESULT = std::pair<ListFilesResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<ListFilesResponse>("ListFiles", srpc::RPCAsyncFutureCallback<ListFilesResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void SRPCClient::CreateFile(const CreateFileRequest *req, CreateFileDone done)
{
	auto *task = this->create_rpc_client_task("CreateFile", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCClient::CreateFile(const CreateFileRequest *req, CreateFileResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_CreateFile(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<CreateFileResponse, srpc::RPCSyncContext>> SRPCClient::async_CreateFile(const CreateFileRequest *req)
{
	using RESULT = std::pair<CreateFileResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<CreateFileResponse>("CreateFile", srpc::RPCAsyncFutureCallback<CreateFileResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void SRPCClient::GetFileForDownload(const GetFileForDownloadRequest *req, GetFileForDownloadDone done)
{
	auto *task = this->create_rpc_client_task("GetFileForDownload", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCClient::GetFileForDownload(const GetFileForDownloadRequest *req, GetFileForDownloadResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_GetFileForDownload(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<GetFileForDownloadResponse, srpc::RPCSyncContext>> SRPCClient::async_GetFileForDownload(const GetFileForDownloadRequest *req)
{
	using RESULT = std::pair<GetFileForDownloadResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<GetFileForDownloadResponse>("GetFileForDownload", srpc::RPCAsyncFutureCallback<GetFileForDownloadResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::SRPCClientTask *SRPCClient::create_ListFiles_task(ListFilesDone done)
{
	return this->create_rpc_client_task("ListFiles", std::move(done));
}

inline srpc::SRPCClientTask *SRPCClient::create_CreateFile_task(CreateFileDone done)
{
	return this->create_rpc_client_task("CreateFile", std::move(done));
}

inline srpc::SRPCClientTask *SRPCClient::create_GetFileForDownload_task(GetFileForDownloadDone done)
{
	return this->create_rpc_client_task("GetFileForDownload", std::move(done));
}

inline SRPCHttpClient::SRPCHttpClient(const char *host, unsigned short port):
	srpc::SRPCHttpClient("cloud/disk/FileMetaService")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::SRPCHttpClient::init(&params);
}

inline SRPCHttpClient::SRPCHttpClient(const struct srpc::RPCClientParams *params):
	srpc::SRPCHttpClient("cloud/disk/FileMetaService")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::SRPCHttpClient::init(temp);
}

inline void SRPCHttpClient::ListFiles(const ListFilesRequest *req, ListFilesDone done)
{
	auto *task = this->create_rpc_client_task("ListFiles", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCHttpClient::ListFiles(const ListFilesRequest *req, ListFilesResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_ListFiles(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<ListFilesResponse, srpc::RPCSyncContext>> SRPCHttpClient::async_ListFiles(const ListFilesRequest *req)
{
	using RESULT = std::pair<ListFilesResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<ListFilesResponse>("ListFiles", srpc::RPCAsyncFutureCallback<ListFilesResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void SRPCHttpClient::CreateFile(const CreateFileRequest *req, CreateFileDone done)
{
	auto *task = this->create_rpc_client_task("CreateFile", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCHttpClient::CreateFile(const CreateFileRequest *req, CreateFileResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_CreateFile(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<CreateFileResponse, srpc::RPCSyncContext>> SRPCHttpClient::async_CreateFile(const CreateFileRequest *req)
{
	using RESULT = std::pair<CreateFileResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<CreateFileResponse>("CreateFile", srpc::RPCAsyncFutureCallback<CreateFileResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void SRPCHttpClient::GetFileForDownload(const GetFileForDownloadRequest *req, GetFileForDownloadDone done)
{
	auto *task = this->create_rpc_client_task("GetFileForDownload", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCHttpClient::GetFileForDownload(const GetFileForDownloadRequest *req, GetFileForDownloadResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_GetFileForDownload(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<GetFileForDownloadResponse, srpc::RPCSyncContext>> SRPCHttpClient::async_GetFileForDownload(const GetFileForDownloadRequest *req)
{
	using RESULT = std::pair<GetFileForDownloadResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<GetFileForDownloadResponse>("GetFileForDownload", srpc::RPCAsyncFutureCallback<GetFileForDownloadResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::SRPCHttpClientTask *SRPCHttpClient::create_ListFiles_task(ListFilesDone done)
{
	return this->create_rpc_client_task("ListFiles", std::move(done));
}

inline srpc::SRPCHttpClientTask *SRPCHttpClient::create_CreateFile_task(CreateFileDone done)
{
	return this->create_rpc_client_task("CreateFile", std::move(done));
}

inline srpc::SRPCHttpClientTask *SRPCHttpClient::create_GetFileForDownload_task(GetFileForDownloadDone done)
{
	return this->create_rpc_client_task("GetFileForDownload", std::move(done));
}

inline BRPCClient::BRPCClient(const char *host, unsigned short port):
	srpc::BRPCClient("cloud.disk.FileMetaService")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::BRPCClient::init(&params);
}

inline BRPCClient::BRPCClient(const struct srpc::RPCClientParams *params):
	srpc::BRPCClient("cloud.disk.FileMetaService")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::BRPCClient::init(temp);
}

inline void BRPCClient::ListFiles(const ListFilesRequest *req, ListFilesDone done)
{
	auto *task = this->create_rpc_client_task("ListFiles", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void BRPCClient::ListFiles(const ListFilesRequest *req, ListFilesResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_ListFiles(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<ListFilesResponse, srpc::RPCSyncContext>> BRPCClient::async_ListFiles(const ListFilesRequest *req)
{
	using RESULT = std::pair<ListFilesResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<ListFilesResponse>("ListFiles", srpc::RPCAsyncFutureCallback<ListFilesResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void BRPCClient::CreateFile(const CreateFileRequest *req, CreateFileDone done)
{
	auto *task = this->create_rpc_client_task("CreateFile", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void BRPCClient::CreateFile(const CreateFileRequest *req, CreateFileResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_CreateFile(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<CreateFileResponse, srpc::RPCSyncContext>> BRPCClient::async_CreateFile(const CreateFileRequest *req)
{
	using RESULT = std::pair<CreateFileResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<CreateFileResponse>("CreateFile", srpc::RPCAsyncFutureCallback<CreateFileResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void BRPCClient::GetFileForDownload(const GetFileForDownloadRequest *req, GetFileForDownloadDone done)
{
	auto *task = this->create_rpc_client_task("GetFileForDownload", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void BRPCClient::GetFileForDownload(const GetFileForDownloadRequest *req, GetFileForDownloadResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_GetFileForDownload(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<GetFileForDownloadResponse, srpc::RPCSyncContext>> BRPCClient::async_GetFileForDownload(const GetFileForDownloadRequest *req)
{
	using RESULT = std::pair<GetFileForDownloadResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<GetFileForDownloadResponse>("GetFileForDownload", srpc::RPCAsyncFutureCallback<GetFileForDownloadResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::BRPCClientTask *BRPCClient::create_ListFiles_task(ListFilesDone done)
{
	return this->create_rpc_client_task("ListFiles", std::move(done));
}

inline srpc::BRPCClientTask *BRPCClient::create_CreateFile_task(CreateFileDone done)
{
	return this->create_rpc_client_task("CreateFile", std::move(done));
}

inline srpc::BRPCClientTask *BRPCClient::create_GetFileForDownload_task(GetFileForDownloadDone done)
{
	return this->create_rpc_client_task("GetFileForDownload", std::move(done));
}

inline TRPCClient::TRPCClient(const char *host, unsigned short port):
	srpc::TRPCClient("cloud.disk.FileMetaService")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::TRPCClient::init(&params);
}

inline TRPCClient::TRPCClient(const struct srpc::RPCClientParams *params):
	srpc::TRPCClient("cloud.disk.FileMetaService")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::TRPCClient::init(temp);
}

inline void TRPCClient::ListFiles(const ListFilesRequest *req, ListFilesDone done)
{
	auto *task = this->create_rpc_client_task("/cloud.disk.FileMetaService/ListFiles", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCClient::ListFiles(const ListFilesRequest *req, ListFilesResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_ListFiles(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<ListFilesResponse, srpc::RPCSyncContext>> TRPCClient::async_ListFiles(const ListFilesRequest *req)
{
	using RESULT = std::pair<ListFilesResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<ListFilesResponse>("/cloud.disk.FileMetaService/ListFiles", srpc::RPCAsyncFutureCallback<ListFilesResponse>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void TRPCClient::CreateFile(const CreateFileRequest *req, CreateFileDone done)
{
	auto *task = this->create_rpc_client_task("/cloud.disk.FileMetaService/CreateFile", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCClient::CreateFile(const CreateFileRequest *req, CreateFileResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_CreateFile(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<CreateFileResponse, srpc::RPCSyncContext>> TRPCClient::async_CreateFile(const CreateFileRequest *req)
{
	using RESULT = std::pair<CreateFileResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<CreateFileResponse>("/cloud.disk.FileMetaService/CreateFile", srpc::RPCAsyncFutureCallback<CreateFileResponse>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void TRPCClient::GetFileForDownload(const GetFileForDownloadRequest *req, GetFileForDownloadDone done)
{
	auto *task = this->create_rpc_client_task("/cloud.disk.FileMetaService/GetFileForDownload", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCClient::GetFileForDownload(const GetFileForDownloadRequest *req, GetFileForDownloadResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_GetFileForDownload(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<GetFileForDownloadResponse, srpc::RPCSyncContext>> TRPCClient::async_GetFileForDownload(const GetFileForDownloadRequest *req)
{
	using RESULT = std::pair<GetFileForDownloadResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<GetFileForDownloadResponse>("/cloud.disk.FileMetaService/GetFileForDownload", srpc::RPCAsyncFutureCallback<GetFileForDownloadResponse>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::TRPCClientTask *TRPCClient::create_ListFiles_task(ListFilesDone done)
{
	auto *task = this->create_rpc_client_task("/cloud.disk.FileMetaService/ListFiles", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline srpc::TRPCClientTask *TRPCClient::create_CreateFile_task(CreateFileDone done)
{
	auto *task = this->create_rpc_client_task("/cloud.disk.FileMetaService/CreateFile", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline srpc::TRPCClientTask *TRPCClient::create_GetFileForDownload_task(GetFileForDownloadDone done)
{
	auto *task = this->create_rpc_client_task("/cloud.disk.FileMetaService/GetFileForDownload", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline TRPCHttpClient::TRPCHttpClient(const char *host, unsigned short port):
	srpc::TRPCHttpClient("cloud.disk.FileMetaService")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::TRPCHttpClient::init(&params);
}

inline TRPCHttpClient::TRPCHttpClient(const struct srpc::RPCClientParams *params):
	srpc::TRPCHttpClient("cloud.disk.FileMetaService")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::TRPCHttpClient::init(temp);
}

inline void TRPCHttpClient::ListFiles(const ListFilesRequest *req, ListFilesDone done)
{
	auto *task = this->create_rpc_client_task("ListFiles", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCHttpClient::ListFiles(const ListFilesRequest *req, ListFilesResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_ListFiles(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<ListFilesResponse, srpc::RPCSyncContext>> TRPCHttpClient::async_ListFiles(const ListFilesRequest *req)
{
	using RESULT = std::pair<ListFilesResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<ListFilesResponse>("ListFiles", srpc::RPCAsyncFutureCallback<ListFilesResponse>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void TRPCHttpClient::CreateFile(const CreateFileRequest *req, CreateFileDone done)
{
	auto *task = this->create_rpc_client_task("CreateFile", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCHttpClient::CreateFile(const CreateFileRequest *req, CreateFileResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_CreateFile(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<CreateFileResponse, srpc::RPCSyncContext>> TRPCHttpClient::async_CreateFile(const CreateFileRequest *req)
{
	using RESULT = std::pair<CreateFileResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<CreateFileResponse>("CreateFile", srpc::RPCAsyncFutureCallback<CreateFileResponse>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void TRPCHttpClient::GetFileForDownload(const GetFileForDownloadRequest *req, GetFileForDownloadDone done)
{
	auto *task = this->create_rpc_client_task("GetFileForDownload", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCHttpClient::GetFileForDownload(const GetFileForDownloadRequest *req, GetFileForDownloadResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_GetFileForDownload(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<GetFileForDownloadResponse, srpc::RPCSyncContext>> TRPCHttpClient::async_GetFileForDownload(const GetFileForDownloadRequest *req)
{
	using RESULT = std::pair<GetFileForDownloadResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<GetFileForDownloadResponse>("GetFileForDownload", srpc::RPCAsyncFutureCallback<GetFileForDownloadResponse>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::TRPCHttpClientTask *TRPCHttpClient::create_ListFiles_task(ListFilesDone done)
{
	auto *task = this->create_rpc_client_task("ListFiles", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline srpc::TRPCHttpClientTask *TRPCHttpClient::create_CreateFile_task(CreateFileDone done)
{
	auto *task = this->create_rpc_client_task("CreateFile", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline srpc::TRPCHttpClientTask *TRPCHttpClient::create_GetFileForDownload_task(GetFileForDownloadDone done)
{
	auto *task = this->create_rpc_client_task("GetFileForDownload", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

} // end namespace FileMetaService

} // end namespace disk

} // end namespace cloud

